### ISSUE TITLE
Is javascript/typescript really the right language for this task?

### ISSUE THREAD

**Issue by impredicative** [GenerousLabs/git-remote-encrypted#2]
Wouldn't you want to use Go, Nim, Rust or another systems language instead?

**Comment by chmac** [comment]
Sorry for the slow response, just spotted your issue. I've enabled better notification settings now.

To match your brevity, the simple answer is, yes. :-)

The key goal is to build something that will work with isomorphic-git, so it's deployable in as wide a range of environments as possible. Of course the same encryption scheme could be rebuilt in another language, and the `git-remote-encrypted` command line tool would no doubt perform better. But right now, there's just 1 tool, and it can run in many environments. That's clearly a winning factor for now.

Would you like to build a compatible version in Go or Rust?

**Comment by impredicative** [comment]
I don't understand how it can run in many environments. Doesn't it require Typescript to be present? Or is the intent to compile it and make it runnable without requiring Typescript?

I am not in a position to reimplement it right now. Currently I have been using git+[gocryptfs](https://github.com/rfjakob/gocryptfs) via [gec](https://github.com/impredicative/gec).

**Comment by impredicative** [comment]
I note two goals:
- [ ] Dependency free binary for use on Linux/MacOS, etc. (without requiring Node)
- [ ] Integration with https://isomorphic-git.org/

The Nim programming language can check off both boxes. Can Typescript check off the first box?

**Comment by chmac** [comment]
Where do you see these goals arising from? From the docs here? Or these are your suggestions?

The underlying aim behind integrating with isomorphic-git is to be able to build offline first, web / mobile applications that use git as an underlying storage and sync mechanism.

The vision, or dream, is to also interop with projects like [pagemarks](https://gitlab.com/barfuin/pagemarks), [nb](https://xwmx.github.io/nb/) and [GitJournal](https://gitjournal.io) so as to have a range of projects that all support markdown files stored in git repos as a backend for useful user facing applications. Thus hopefully allowing users easier data transport between services, easier replication onto a desktop or other computer via git, and so on.

Nim looks like an interesting language. If you're interested in writing an alternative git-remote-encrypted client in nim, I'd be super happy to try and support that.

**Comment by impredicative** [comment]
Your repo seems misnamed, and should probably have `js` somewhere in the name, perhaps as `git-remote-encrypted.js`. To be clear, until you rename the repo, you're doing nothing for non-js users, just burdening them with potential js baggage that they don't need.

To repeat myself, the stated vision and the readme are hugely discordant.

**Comment by chmac** [comment]
To be clear, nowhere does it state that we aim to ship a single, dependency free binary. If you can link to where that is stated, I'll be glad to correct it, as it's definitely not a current goal.

If you're interested in contributing to this work, I'll be happy to support you in that. If not, then I'm happy to close this discussion here.
