### ISSUE TITLE
Fix incorrect link in readme

### ISSUE THREAD

**Issue by impredicative** [GenerousLabs/git-remote-encrypted#7]
> Inspired by git-remote-gcrypt

In the readme, in the line quoted above, git-remote-gcrypt links to https://github.com/GenerousLabs/git-remote-encrypted/blob/master which is broken and incorrect. Anyway, claiming inspiration looks to be a stretch since the goals of this project seem sufficiently different.

**Comment by chmac** [comment]
Thanks.
